### ISSUE TITLE
Deal with stale issues from -core

### ISSUE THREAD

**Issue by mih** [datalad/datalad-revolution#36]
- [x] `save(version_tag=)` fails when not in root of repo https://github.com/datalad/datalad/issues/2430
- [ ] add could crash due to expanded list of files to be too long https://github.com/datalad/datalad/issues/1883
- [x] datalad/datalad#2851
- [x] Adding new (deep) subdatasets broken on win v6 datalad/datalad#2857

**Comment by mih** [comment]
Obsolete tracking issue...closing
