### ISSUE TITLE
ROADMAP

### ISSUE THREAD

**Issue by mih** [datalad/datalad-revolution#44]
This is the roadmap outline for this extension. At the very minimum, it will have to remain an extension until -core drops support for direct mode (for the mere fact that there is no direct mode support whatsoever in this code, and it will stay this way due to the monumental cost that would need to be paid for virtually no benefit). When that happens, one would have to see how many other pieces have accumulated this extension as a dependency. The more will have done at that point, the more disruptive a potential future merge into -core would be for them.

#### Development goals

- [x] no code in this extension uses path annotation
- [x] absolutely minimize special-casing windows in this code base (ATM there is a single `on_windows` that is unavoidable due to https://github.com/datalad/datalad/issues/2955), if special-casing is needed, test for the actual requirement (e.g. symlink availability) rather than the platform.
  - [ ] implement a facility that lazily tests for capabilities and that can be queried -- ATM only relevant for the tests, but would be used in `wtf` and error messaging in general too https://github.com/datalad/datalad/issues/2553
- [x] have a `status` command that reports a comprehensive state of a dataset (hierarchy) in an efficient way -- this is fundamentally different from path annotation as it solely relies on Git for queries and does not try to infer information from the situation in the worktree
  - [x] design other commands and low-level functions to be able to work with the status report and act on it without having to perform additional (costly) queries if anyhow avoidable
  - [x] cache status information whenever the same info would need to be acquired multiple times
- [x] design in the spirit of https://github.com/datalad/datalad/issues/2765 -- a few commands with a somewhat minimal API that a users needs to worry about. Rely on configuration settings rather than tons of API options.
  - [x] a `create` command (very origin of any dataset)
  - [x] a `save` command that is the **only** required command to handle any additional or removal to/from a dataset. This makes it possible for users to use any tool UI to interact with a datasets and
just run `save` periodically
    - [x] replace core `save`
    - [x] replace core `add`
    - [x] replace core `remove` (see #43) -- in quotes as the users will have a hard time to wipe out an annex of a subdataset with anything other than datalad (at least on linux)
  - [x] have `run` exercise the -revolution code stack and avoid -core `add`
  - [x] make run (and/or its tests) run on windows
- [x] produce docs to show off this mode of operation
  - [ ] Make the connection to a (tuned) YODA-like dataset preconfiguration, and then just add and remove stuff at will. Point out that YODA asks for outputs to appear at the top-level and a `save` is enough (and safer), but a `save(recursive)` exists and can be used.
  - [x] integrate these docs with docs.datalad.org
  - [x] put demo on datalad.org (waiting for approval)
- [x] reimplement the `diff` command to be able to act on changes in a dataset (hierarchy) -- see `--since` option in some -core commands
  - [x] have `.diff()` analog to `.status()` on the repo level using highly similar data structures for their report
- [ ] port `install`, `clone`, `get` tests from -core to work on windows. In -core those rely on the testrepo setup that is broken on windows and all tests using it (which is most) are just skipped (test of "just use them as is" failed in #42)
- [ ] implement some kind of "worker management" to be able to support (on-demand) parallelization without having to expose individual API arguments to decide on whether a particular pieces should go parallel, rather than the whole beast making use of parallelization in general (see e.g. #32)

This roadmap will be extended as needed.

**Comment by mih** [comment]
The revolution is over. Reopen if someone re-kindles the fires.
